version: '3.8'

services:
  web:
    container_name: kiii-web
    image: kiii-web:latest
    build: .
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./config/application.properties:/app/src/main/resources/application.properties

  db:
    image: postgres:latest
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: anastasija
      POSTGRES_DB: kiii
    restart: unless-stopped
